In [2]:
import pandas as pd

In [6]:
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
 12  Age_Group      1000 non-null   category
 13  Month          1000 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 102.9+ KB

In [18]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age               0
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
Age_Group         0
Month             0
dtype: int64

In [19]:

df.duplicated().sum()

0

In [20]:

df.describe()

,Order_Date,Age,Quantity,Unit_Price,Total_Sales
count,1000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2025-07-03 11:19:40.800000,41.353000,5.435000,25486.783410,139399.439650
min,2025-01-01 00:00:00,18.000000,1.000000,145.780000,437.340000
25%,2025-03-30 18:00:00,30.000000,3.000000,13895.722500,47066.632500
50%,2025-07-01 00:00:00,41.000000,5.000000,25398.740000,108594.025000
75%,2025-10-07 06:00:00,53.000000,8.000000,37512.382500,203722.882500
max,2026-01-01 00:00:00,65.000000,10.000000,49997.530000,493677.500000
std,NaN,13.683626,2.838632,14179.402361,114100.051546

In [21]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [23]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [24]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,25,40,60,100],
    labels=["Young","Adult","Middle Age","Senior"]
)

In [25]:
df.to_csv("Cleaned_Sales_Dataset.csv", index=False)

print("Cleaning Completed Successfully!")

Cleaning Completed Successfully!

In [26]:
df["Month"] = df["Order_Date"].dt.month_name()

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,25,40,60,100],
    labels=["Young","Adult","Middle Age","Senior"]
)

In [27]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [28]:
print("Missing Values After Cleaning:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values After Cleaning:
Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
Age_Group        0
Month            0
dtype: int64

Duplicate Rows:
0

In [29]:
df.to_csv("Cleaned_Sales_Dataset.csv", index=False)
print("File Saved Successfully")

File Saved Successfully